<Project>
    <PropertyGroup>
        <Description>The cross-platform graphics toolkit.</Description>
        <RepositoryUrl>https://github.com/Aquatic-Games/Pie</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Authors>aquagoose</Authors>
        <!--<PackageProjectUrl>https://piegfx.com/pie/</PackageProjectUrl>--> <!-- piegfx.com... yikes... -->
        <PackageTags>graphics;opengl;directx;vulkan;cross-platform;audio;freetype;text;sdl</PackageTags>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
</Project>